Add consent manager
Esri/solutions-components pull request #594
Opened 2024-03-20 18:56 UTC by jmhauck

2024-03-20 19:33 UTC, MikeTschudi requested changes

2024-03-20 19:33 UTC, MikeTschudi commented on src/components/consent-manager/consent-manager.tsx
> +            </div>
Lines 189 to 216 are not internationalizable.

The English "...we invite you to read our" + " " + "data protection policy..." translates to "...laden wir Sie ein, unsere zu lesen" + " " + "Datenschutzrichtlinie..." in German, but the "zu lesen" actually belongs at the end of the whole sentence: "...unseren Cookie-Bestand zu lesen."

The sentence needs to be complete, with placeholders used to indicate where the links are. I sent a request on the Translations Teams channel asking how to do this.

2024-03-27 18:52 UTC, jmhauck commented
@MikeTschudi I'd like to go ahead with this even though we don't have that detail worked out yet so I can do a publish to npm and get in an initial PR for the deployment app

2024-03-27 18:54 UTC, MikeTschudi approved these changes

2024-03-27 18:58 UTC, merged