Connect JSON editor to modal
Esri/solutions-components pull request #84
Opened 2022-10-21 19:36 UTC by MikeTschudi

* Valid changes in the JSON editor
  * activate the Cancel & Save modal buttons
  * are snapshotted to the underlying component store
* Invalid changes in the JSON
  * are flagged as an error in the editor
  * disable the Cancel & Save modal buttons regardless of the state of changes in the solution
  * are not snapshotted

Snapshots are kept even as one switches among solution items.

2022-10-21 20:37 UTC, jmhauck requested changes

2022-10-21 20:37 UTC, jmhauck commented on src/components/json-editor/json-editor.tsx
> +    window.dispatchEvent(new CustomEvent("solutionEditorContentChanged", {
@MikeTschudi does dispatchEvent allow us to do something that stencils EventEmitter doesn't?

2022-10-21 20:37 UTC, jmhauck commented on src/components/json-editor/json-editor.tsx
> +  protected _flagEditorHasErrors(flagHasErrors: boolean): void {
doc here as well

2022-10-21 20:37 UTC, jmhauck commented on src/components/json-editor/json-editor.tsx
> +  protected _flagEditorHasChanges(flagHasChanges: boolean): void {
could you doc the arg please

2022-10-21 20:37 UTC, jmhauck commented on src/components/solution-configuration/solution-configuration.tsx
> +  constructor() {
@MikeTschudi similar thing here with addEventListener vs stencils @ Listen...is this done for a particular reason?

2022-10-21 20:37 UTC, jmhauck commented on src/components/solution-configuration/solution-configuration.tsx
> +  protected _updateSaveability(
doc?

2022-10-21 20:37 UTC, jmhauck commented on src/components/solution-template-data/solution-template-data.tsx
> +    window.addEventListener("solutionEditorContentChanged",
same thing here with addEventListener vs Listen

2022-10-21 20:37 UTC, jmhauck commented on src/demos/new-solution-configuration.html
> +          window.addEventListener("solutionCanSave",
addEventListener vs Listen

2022-10-21 20:37 UTC, jmhauck commented on src/utils/solution-store.ts
> +  protected _flagStoreHasChanges(flagHasChanges: boolean): void {
doc arg

2022-10-21 20:40 UTC, MikeTschudi commented on src/components/json-editor/json-editor.tsx
> +    window.dispatchEvent(new CustomEvent("solutionEditorContentChanged", {
It does less in that StencilJS handles deallocating listeners for us with the @Event/@Listener markers, but I haven't been able to get them to work

2022-10-24 14:24 UTC, jmhauck approved these changes

2022-10-24 14:55 UTC, merged